# replace clock_bridge
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
  lazy: false

# replace odom_tf_bridge 
# - ros_topic_name: "tf"
#   gz_topic_name: "/model/drone/pose_static"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS
#   lazy: false

# replace ground_truth 
- ros_topic_name: "ground_truth"
  gz_topic_name: "/model/drone/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
  lazy: false

# replace IMU
- ros_topic_name: "imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  lazy: false

# replace BAROMETER
- ros_topic_name: "barometer/data"
  gz_topic_name: "/pressure"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "gz.msgs.FluidPressure"
  direction: GZ_TO_ROS
  lazy: false

# replace Motors
- ros_topic_name: "drone/command/motor_speed"
  gz_topic_name: "/drone/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ
  lazy: false
  qos_profile: SENSOR_DATA